name: Full_Regression_Manual

#on:
#  push:
#    branches:
#      - "master" # Will start the job every time after push into master branch
#  schedule:
#    - cron: "0 0 * * *" # Automatic start to run the job at the scheduled time at 00:00 UTC
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install Chrome and WebDriver
        run: |
            brew install --cask google-chrome
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          python -m pytest -n 2 --dist loadgroup --verbose --junit-xml=test-results.xml
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: '**/test-results.xml'
          detailed_summary: true
          include_passed: true
