name: Full_regression_schedule_and_push

on:
  push:
    branches:
      - "master"
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install Chrome and WebDriver
        run: |
            brew install --cask google-chrome
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          python pytest -n 2 --dist loadgroup --verbose --junit-xml=test-results.xml
#      - name: Lint code with Pylint
#        run: |
#          pylint --rcfile=.pylintrc tests
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: '**/test-results.xml'
          detailed_summary: true
          include_passed: true
